---
- hosts: nodo1
  become: yes
  name: Instalar y Configurar PostgreSQL y Bind9
  tasks:
  - name: Variables
    include_vars:
      file: vars
  - name: Actualizar lista de paquetes
    apt: update_cache=yes
  - name: Comprobar que Bind9 está instalado correctamente    
    apt: name=bind9 state=latest
  - name: Configuración del fichero named.conf.local
    template:
      src: named-conf-local.j2
      dest: /etc/bind/named.conf.local
  - name: Configuración del fichero /var/cache/bind/db.example.com
    template:
      src: var-cache-bind.j2
      dest: /var/cache/bind/db.expample.com
    notify: Reiniciar servicio dns Bind9
  - name: Comprobar que PostgreSQL está instalado correctamente
    apt: name={{ item }} update_cache=true state=installed
    with_items:
     - postgresql
     - postgresql-contrib
     - libpq-dev
     - python-psycopg2
     - postgresql-client
    tags: packages
#  - name: Creación de base de datos en PostgreSQL
#    shell:
#  - name: Creación de usuario en la base de datos de PostgreSQL
#    shell:
#  - name: Dar privilegios al usuario creado hacia la base de datos creada en PostgreSQL
#    shell:

- hosts: nodo2
  become: yes
  name: Instalar y Configurar Apache2
  tasks:
  - name: Variables 2
    include_vars:
      file: vars
  - name: Actualizar lista de paquetes
    apt: update_cache=yes
  - name: Comprobar que Apache2 está instalado correctamente
    apt: name=apache2 state=latest
  - name: Comprobar que el módulo PHP7.0-FPM está instalado correctamente
    apt: name=php7.0-fpm state=latest
    apt:
      name: "{{ item }}"
    with_items:
     - php7.0
     - php7.0-common
     - php7.0-readline
     - php7.0-fpm
     - php7.0-cli
     - php7.0-gd
     - php7.0-mcrypt
     - php7.0-curl
     - php7.0-mbstring
     - php7.0-opcache
     - php7.0-json
    tags: packages
  - name: Instalar unzip en el equipo Servidor
    apt: name=unzip state=latest
  - name: Descargar drupal en el equipo Servidor
    get_url:
      url: https://ftp.drupal.org/files/projects/drupal-8.6.7.zip
      dest: /home/vagrant/drupal-8.6.7.zip
  - name: Descomprimir CMS drupal
    unarchive:
      src: /home/vagrant/drupal-8.6.7.zip
      dest: /var/www
      remote_src: yes
      owner: www-data
      group: www-data 
  - name: Configurar virtualhost del sitio web de drupal
    template:
      src: 000-default-conf.j2
      dest: /etc/apache2/sites-available/000-default.conf    
    notify: Reiniciar servicio web Apache   
  handlers:
  - name: Reiniciar servicio web Apache
    service: 
      name: apache2
      state: restarted
      become: yes
#  - name: Reiniciar SGBD PostgreSQL
#    sercive:
#      name: postgresql
#      state: restarted
#      become: yes
#  - name: Reiniciar servicio dns Bind9
#    service:
#      name: bind9
#      state: restarted
#      become: yes
