---
- hosts: nodo2
  become: yes
  name: Instalar y Configurar Apache2
  tasks:
  - name: Actualizar lista de paquetes
    apt: update_cache=yes
  - name: Instalar servidor Web Apache2
    apt: 
      name= "{{ item }}"
    with_items:
     - apache2
     - apache-utils
    tags: packages
  - name: Instalar módulo PHP7.0-FPM para servidor Web Apache2
    apt:
      name: "{{ item }}"
    with_items:
     - libapache2-mod-php7.0
     - php7.0
     - php7.0-fpm
     - php-pgsql
     - php7.0-dom
     - php7.0-gd
     - php7.0-xml
     - php7.0-mbstring
    tags: packages
  - name: Instalar cliente de PostgrSQL en el equipo Servidor
    apt: name=postgresql-client state=latest
  - name: Descargar drush en el equipo Servidor
    get_url:
      url: https://github.com/drush-ops/drush/releases/download/8.1.17/drush.phar
      dest: /home/vagrant/drush.phar
  - name: Renombrar fichero drush descargado previamente
    command: mv drush.phar drush
  - name: Mover fichero drush al directorio /usr/local/bin/
    command: mv drush /usr/local/bin/drush
  - name: Dar permiso de ejecución al fichero drush
    command: chmod +x /usr/local/bin/drush
  - name: Instalar unzip en el equipo Servidor
    apt: name=unzip state=latest
  - name: Descargar drupal en el equipo Servidor
    get_url:
      url: https://ftp.drupal.org/files/projects/drupal-8.6.7.zip
      dest: /home/vagrant/drupal-8.6.7.zip
  - name: Descomprimir CMS drupal
    unarchive:
      src: /home/vagrant/drupal-8.6.7.zip
      dest: /var/www/html
      remote_src: yes
      owner: www-data
      group: www-data
      mode : 0755
  - name: Configurar virtualhost del sitio web de drupal
    copy: >
      src=files/apache2/etc/apache2/sites-available/drupal.conf
      dest=/etc/apache2/sites-available/drupal.conf
  - name: Deshabilitar sitio web por defecto de Apache2
    command: a2dissite 000-default.conf
  - name: Habilitar sitio web de drupal
    command: a2ensite drupal.conf
  - name: Habilitar modulo fast_cgi
    command: a2enmod proxy_fcgi
  - name: Habilitar configuración de PHP7.0-FPM
    command: a2enconf php7.0-fpm
  - name: Instalar drupal con drush    
    command: > 
      drush si standard -y
      --site-name="Drupal de Kevin Ariza"
      --account-name="drupal"
      --account-pass="drupal"
      --db-url=pgsql://drupal:drupal@10.0.100.2/drupal
      -r /var/www/html/drupal-8.6.7 -y
  - name: Deshabilitar agregación de CSS con drush
    command: drush config-set system.performance css.preprocess 0 -r /var/www/html/drupal-8.6.7 -y
  - name: Deshabilitar agregación de JS con drush
    command: drush config-set system.performance js.preprocess 0 -r /var/www/html/drupal-8.6.7 -y
    notify: 
     - Reiniciar servicio web Apache
  handlers:
  - name: Reiniciar servicio web Apache
    service: 
      name=apache2
      state=restarted
