---
- hosts: nodo2
  become: yes
  name: Instalar y Configurar Apache2
  tasks:
  - name: Actualizar lista de paquetes
    apt: update_cache=yes
  - name: Instalar servidor Web Apache2
    apt: 
      name= "{{ item }}"
    with_items:
     - apache2
     - apache-utils
    tags: packages
  - name: Instalar módulo PHP7.0-FPM para servidor Web Apache2
    apt:
      name: "{{ item }}"
    with_items:
     - libapache2-mod-php7.0
     - php7.0
     - php7.0-fpm
     - php-pgsql
     - php7.0-dom
     - php7.0-gd
     - php7.0-xml
     - php7.0-mbstring
    tags: packages
  - name: Instalar unzip en el equipo Servidor
    apt: name=unzip state=latest
  - name: Descargar drupal en el equipo Servidor
    get_url:
      url: https://ftp.drupal.org/files/projects/drupal-8.6.7.zip
      dest: /home/vagrant/drupal-8.6.7.zip
  - name: Descomprimir CMS drupal
    unarchive:
      src: /home/vagrant/drupal-8.6.7.zip
      dest: /var/www/html
      remote_src: yes
      owner: www-data
      group: www-data
      mode : 0755
  - name: Configurar virtualhost del sitio web de drupal
    copy: >
      src=files/apache2/etc/apache2/sites-available/drupal.conf
      dest=/etc/apache2/sites-available/drupal.conf
  - name: Deshabilitar sitio web por defecto de Apache2
    command: a2dissite 000-default.conf
  - name: Habilitar sitio web de drupal
    command: a2ensite drupal.conf
  - name: Habilitar modulo fast_cgi
    command: a2enmod proxy_fcgi
  - name: Habilitaar configuración de PHP7.0-FPM
    command: a2enconf php7.0-fpm    
    notify: 
     - Reiniciar servicio web Apache
  handlers:
  - name: Reiniciar servicio web Apache
    service: 
      name=apache2
      state=restarted
